
        // O2 UNITY AUTO ASSET MAPPER
        // ==============================
        // Auto Generated Mapper Script
        //
        // WARNING:
        // - This file is automatically generated. Do NOT modify manually unless you know what you are doing.
        // Purpose:
        // This class provides mapping between keys and addressable assets for UI LevelData.
        //
        // ==============================
        // Generated 1.0 10/13/2025 5:47:08 PM
        using UnityEngine.AddressableAssets;
        using UnityEngine.ResourceManagement.AsyncOperations;

        public class LevelDataMapper : BaseMapper<LevelData, LevelDataAssetKey> {
            public override string KeyScript => "LevelData.Keys.g";
            static LevelDataMapper @default;

            [UnityEngine.Scripting.Preserve]
            public static LevelDataMapper Default {
                get {
                    if (@default)
                        return @default;

                    AsyncOperationHandle<LevelDataMapper> handle =
                        Addressables.LoadAssetAsync<LevelDataMapper>(
                            "GeneratedMapper_LevelData");
                    handle.WaitForCompletion();
                    @default = handle.Result;
                    return @default;
                }
            }
     

            public static LevelData GetMappedAssetAt(int index) {
                if (index < 0 || index >= Default.Assets.Count) {
                    UnityEngine.Debug.LogError($"Index {index} is out of bounds for LevelDataMapper.");
                    return null;
                }
                return Default[index];
            }

            public static LevelData GetMappedAsset(LevelDataAssetKey key) {
                return Default.GetMappedAssetViaKey(key);
            }
        }
    