using System;

public static partial class MapGenerator {
    const string MapperBody = @"
        // O2 UNITY AUTO ASSET MAPPER
        // ==============================
        // Auto Generated Mapper Script
        //
        // WARNING:
        // - This file is automatically generated. Do NOT modify manually unless you know what you are doing.
        // Purpose:
        // This class provides mapping between keys and addressable assets for UI {1}.
        //
        // ==============================
        // Generated 1.0 {3}
        using UnityEngine.AddressableAssets;
        using UnityEngine.ResourceManagement.AsyncOperations;

        public class {0}Mapper : BaseMapper<{1}, {0}AssetKey> {{
            public override string KeyScript => ""{0}.Keys.g"";
            static {0}Mapper @default;

            [UnityEngine.Scripting.Preserve]
            public static {0}Mapper Default {{
                get {{
                    if (@default)
                        return @default;

                    AsyncOperationHandle<{0}Mapper> handle =
                        Addressables.LoadAssetAsync<{0}Mapper>(
                            ""{2}"");
                    handle.WaitForCompletion();
                    @default = handle.Result;
                    return @default;
                }}
            }}
     

            public static {1} GetMappedAssetAt(int index) {{
                if (index < 0 || index >= Default.Assets.Count) {{
                    UnityEngine.Debug.LogError($""Index {{index}} is out of bounds for {0}Mapper."");
                    return null;
                }}
                return Default[index];
            }}

            public static {1} GetMappedAsset({0}AssetKey key) {{
                return Default.GetMappedAssetViaKey(key);
            }}
        }}
    ";


    static string GetMapperSource(string mapName, string assetTypeName, string label) {
        return string.Format(MapperBody, mapName, assetTypeName, label, DateTime.Now);
    }
}