
        // O2 UNITY AUTO ASSET MAPPER
        // ==============================
        // Auto Generated Mapper Script
        //
        // WARNING:
        // - This file is automatically generated. Do NOT modify manually unless you know what you are doing.
        // Purpose:
        // This class provides mapping between keys and addressable assets for UI VFXPair.
        //
        // ==============================
        // Generated 1.0 10/13/2025 1:34:02 AM
        using UnityEngine.AddressableAssets;
        using UnityEngine.ResourceManagement.AsyncOperations;

        public class VFXPairMapper : BaseMapper<VFXPair, VFXPairAssetKey> {
            public override string KeyScript => "VFXPair.Keys.g";
            static VFXPairMapper @default;

            [UnityEngine.Scripting.Preserve]
            public static VFXPairMapper Default {
                get {
                    if (@default)
                        return @default;

                    AsyncOperationHandle<VFXPairMapper> handle =
                        Addressables.LoadAssetAsync<VFXPairMapper>(
                            "GeneratedMapper_VFXPair");
                    handle.WaitForCompletion();
                    @default = handle.Result;
                    return @default;
                }
            }
     

            public static VFXPair GetMappedAssetAt(int index) {
                if (index < 0 || index >= Default.Assets.Count) {
                    UnityEngine.Debug.LogError($"Index {index} is out of bounds for VFXPairMapper.");
                    return null;
                }
                return Default[index];
            }

            public static VFXPair GetMappedAsset(VFXPairAssetKey key) {
                return Default.GetMappedAssetViaKey(key);
            }
        }
    