
        // O2 UNITY AUTO ASSET MAPPER
        // ==============================
        // Auto Generated Mapper Script
        //
        // WARNING:
        // - This file is automatically generated. Do NOT modify manually unless you know what you are doing.
        // Purpose:
        // This class provides mapping between keys and addressable assets for UI UnityEngine.AudioClip.
        //
        // ==============================
        // Generated 1.0 10/13/2025 12:55:08 AM
        using UnityEngine.AddressableAssets;
        using UnityEngine.ResourceManagement.AsyncOperations;

        public class SFXMapper : BaseMapper<UnityEngine.AudioClip, SFXAssetKey> {
            public override string KeyScript => "SFX.Keys.g";
            static SFXMapper @default;

            [UnityEngine.Scripting.Preserve]
            public static SFXMapper Default {
                get {
                    if (@default)
                        return @default;

                    AsyncOperationHandle<SFXMapper> handle =
                        Addressables.LoadAssetAsync<SFXMapper>(
                            "GeneratedMapper_SFX");
                    handle.WaitForCompletion();
                    @default = handle.Result;
                    return @default;
                }
            }
     

            public static UnityEngine.AudioClip GetMappedAssetAt(int index) {
                if (index < 0 || index >= Default.Assets.Count) {
                    UnityEngine.Debug.LogError($"Index {index} is out of bounds for SFXMapper.");
                    return null;
                }
                return Default[index];
            }

            public static UnityEngine.AudioClip GetMappedAsset(SFXAssetKey key) {
                return Default.GetMappedAssetViaKey(key);
            }
        }
    