
        // O2 UNITY AUTO ASSET MAPPER
        // ==============================
        // Auto Generated Mapper Script
        //
        // WARNING:
        // - This file is automatically generated. Do NOT modify manually unless you know what you are doing.
        // Purpose:
        // This class provides mapping between keys and addressable assets for UI StackAsset.
        //
        // ==============================
        // Generated 1.0 10/10/2025 7:24:35 PM
        using UnityEngine.AddressableAssets;
        using UnityEngine.ResourceManagement.AsyncOperations;

        public class StackAssetMapper : BaseMapper<StackAsset, StackAssetAssetKey> {
            public override string KeyScript => "StackAsset.Keys.g";
            static StackAssetMapper @default;

            [UnityEngine.Scripting.Preserve]
            public static StackAssetMapper Default {
                get {
                    if (@default)
                        return @default;

                    AsyncOperationHandle<StackAssetMapper> handle =
                        Addressables.LoadAssetAsync<StackAssetMapper>(
                            "GeneratedMapper_StackAsset");
                    handle.WaitForCompletion();
                    @default = handle.Result;
                    return @default;
                }
            }
     

            public static StackAsset GetMappedAssetAt(int index) {
                if (index < 0 || index >= Default.Assets.Count) {
                    UnityEngine.Debug.LogError($"Index {index} is out of bounds for StackAssetMapper.");
                    return null;
                }
                return Default[index];
            }

            public static StackAsset GetMappedAsset(StackAssetAssetKey key) {
                return Default.GetMappedAssetViaKey(key);
            }
        }
    