using UnityEngine;

// This class is used to mark scriptable objects that are auto-generated.
// It also has a custom editor that allows you to open the key script directly from the inspector.
public abstract class AutoGeneratedScriptable : ScriptableObject {
    public abstract string KeyScript { get; }
}