
        // O2 UNITY AUTO ASSET MAPPER
        // ==============================
        // Auto Generated Mapper Script
        //
        // WARNING:
        // - This file is automatically generated. Do NOT modify manually unless you know what you are doing.
        // Purpose:
        // This class provides mapping between keys and addressable assets for UI ProjectileAsset.
        //
        // ==============================
        // Generated 1.0 10/10/2025 4:44:20 PM
        using UnityEngine.AddressableAssets;
        using UnityEngine.ResourceManagement.AsyncOperations;

        public class ProjectileAssetMapper : BaseMapper<ProjectileAsset, ProjectileAssetAssetKey> {
            public override string KeyScript => "ProjectileAsset.Keys.g";
            static ProjectileAssetMapper @default;

            [UnityEngine.Scripting.Preserve]
            public static ProjectileAssetMapper Default {
                get {
                    if (@default)
                        return @default;

                    AsyncOperationHandle<ProjectileAssetMapper> handle =
                        Addressables.LoadAssetAsync<ProjectileAssetMapper>(
                            "GeneratedMapper_ProjectileAsset");
                    handle.WaitForCompletion();
                    @default = handle.Result;
                    return @default;
                }
            }
     

            public static ProjectileAsset GetMappedAssetAt(int index) {
                if (index < 0 || index >= Default.Assets.Count) {
                    UnityEngine.Debug.LogError($"Index {index} is out of bounds for ProjectileAssetMapper.");
                    return null;
                }
                return Default[index];
            }

            public static ProjectileAsset GetMappedAsset(ProjectileAssetAssetKey key) {
                return Default.GetMappedAssetViaKey(key);
            }
        }
    